= bitcoinj Add-ons 
Sean Gilligan <https://github.com/msgilligan>
v0.2.4
:description: bitcoinj-addons README document.
:addons-version: 0.2.4
:bitcoinj-version: 0.14.4

image:https://travis-ci.org/msgilligan/bitcoinj-addons.svg?branch=master["Build Status", link="https://travis-ci.org/msgilligan/bitcoinj-addons"] image:https://api.bintray.com/packages/msgilligan/maven/bitcoinj-addons/images/download.svg[link="https://bintray.com/msgilligan/maven/bitcoinj-addons/_latestVersion"] 

Add-on modules for https://bitcoinj.github.io[bitcoinj], including:

* A *JSON-RPC Java client* for the https://bitcoin.org/en/developer-reference#bitcoin-core-apis[Bitcoin Core API]
* JSON library using https://github.com/FasterXML/jackson[Jackson] to convert between Bitcoin types and JSON
** *bitcoinj* types <--> JSON (e.g. https://bitcoinj.github.io/javadoc/0.14.3/org/bitcoinj/core/Address.html[Address], https://bitcoinj.github.io/javadoc/0.14.3/org/bitcoinj/core/Sha256Hash.html[Sha256Hash], https://bitcoinj.github.io/javadoc/0.14.3/org/bitcoinj/core/Transaction.html[Transaction])
** Strongly typed http://msgilligan.github.io/bitcoinj-addons/apidoc/com/msgilligan/bitcoinj/json/pojo/package-summary.html[Java POJOs] <--> Bitcoin Core standard JSON (e.g. http://msgilligan.github.io/bitcoinj-addons/apidoc/com/msgilligan/bitcoinj/json/pojo/BlockChainInfo.html[BlockChainInfo], http://msgilligan.github.io/bitcoinj-addons/apidoc/com/msgilligan/bitcoinj/json/pojo/UnspentOutput.html[UnspentOutput], http://msgilligan.github.io/bitcoinj-addons/apidoc/com/msgilligan/bitcoinj/json/pojo/ChainTip.html[ChainTip])
* https://spring.io[Spring] and https://github.com/google/guice[Guice]-compatible Bitcoin server components for *server-side JSON-RPC*.
* **bitcoinj-proxy** - A high-performance, non-blocking https://ratpack.io[Ratpack] server for proxying access to *bitcoind* or building Bitcoin-based microservices.
* **bitcoinj-daemon** - A *Spring Boot*-based framework for a Java-based implementation of *bitcoind*.
* **bitcoinj-peerserver** -  A *Spring Boot*-based web application that connects to the Bitcoin P2P network and streams events to a browser using the *STOMP* protocol over *WebSocket*.
* Bitcoin currency and exchange implementations for http://javamoney.github.io[JavaMoney].
* *bitcoinj-cli* - a command line tool and supporting libraries for accessing the JSON-RPC API.
* A Groovy-language *Domain Specific Language* for scripting and testing with *bitcoinj*
* Functional tests of bitcoind (and bitcoinj-daemon) JSON-RPC services, that run in https://bitcoinj.github.io/testing#regression-test-mode[regression test mode].

WARNING: Do not use this software with your Bitcoin private keys without doing a rigorous audit of the code. (Feedback welcome.)

WARNING: The API is not final and *may* change without warning (we try to deprecate first).

We're hoping that one or more modules will be accepted into the bitcoinj project. Most of these components are fairly new, but all are useful and ready for pull requests.

== Overview

=== Binaries image:https://api.bintray.com/packages/msgilligan/maven/bitcoinj-addons/images/download.svg[link="https://bintray.com/msgilligan/maven/bitcoinj-addons/_latestVersion"]

Although the API is changing, binary releases are available on https://bintray.com/msgilligan/maven/bitcoinj-addons/view[Bintray]. You can download JARs or use the provided Maven coordinates to link to them directly from your `pom.xml` or `build.gradle`.


=== API Documentation

We have published http://msgilligan.github.io/bitcoinj-addons/apidoc/index.html[preliminary JavaDoc] to our Github pages site.

=== Continuous Integration 

bitcoinj-addons is used by https://github.com/OmniLayer/OmniJ#omnij-project[OmniJ] and is tested by the https://ci.omni.foundation/[Omni Foundation Continuous Integration Server] (self-signed SSL certificate). You can check the https://ci.omni.foundation/job/bitcoinj-addons/[bitcoinj-addons job] for build status.


// Jenkins Widget doesn't display correctly because of ci.omni.foundation self-signed SSL
// image:https://ci.omni.foundation/buildStatus/icon?job=bitcoinj-addons[link="https://ci.omni.foundation/job/bitcoinj-addons/"]

There is also a Travis CI build:
image:https://travis-ci.org/msgilligan/bitcoinj-addons.svg?branch=master["Build Status", link="https://travis-ci.org/msgilligan/bitcoinj-addons"]


=== Requirements

* Most modules use JDK 7 (subset) for Android compatibility (see table, below)
* Server modules and Spring Boot Apps require JDK 8 or later

=== Modules

See the table below for an overview of the modules.
The *JDK* column indicates the version of Java required.
The *Grooviness* column describes the use of the http://www.groovy-lang.org[Groovy Programming Language] within that module.

.Modules
[cols="3,1,3,5"]
|===
|Name |JDK |Grooviness |Description

|<<bitcoinj-cli,bitcoinj-cli>>
|7
|Tests only
|Command line RPC tool and CLI support/utility classes

|<<bitcoinj-rpcclient,bitcoinj-rpcclient>>
|7
|Optional + tests
|Bitcoin JSON-RPC client

|<<bitcoinj-json,bitcoinj-json>>
|7
|Tests only (TBD)
|Jackson serializers, deserializers & POJOs for Bitcoin JSON-RPC

|<<bitcoinj-server,bitcoinj-server>>
|8
|Tests only (TBD)
|Service objects used by the server apps 

|<<bitcoinj-proxy,bitcoinj-proxy>>
|8
|Tests only (TBD)
|Ratpack-based server for proxying *bitcoind* and/or building microservices.

|<<bitcoinj-daemon,bitcoinj-daemon>>
|8
|Tests only (TBD)
|JSON-RPC bitcoin server daemon -- to replace `bitcoind` someday ;)

|<<bitcoinj-peerserver,bitcoinj-peerserver>>
|8
|Tests only (TBD)
|Peer and transaction info over HTTP + WebSocket/STOMP. JSON-RPC server, too.

|<<bitcoinj-money,bitcoinj-money>>
|7
|Tests only (TBD)
|http://javamoney.github.io[JavaMoney] currency and exchange support. Adapter to use http://knowm.org/open-source/xchange/[XChange] `Exchange` implementations as JavaMoney `ExchangeRateProvider`s.

|<<bitcoinj-dsl,bitcoinj-dsl>>
|7
|Uses Groovy
|Groovy DSL support.

|<<bitcoinj-spock,bitcoinj-spock>>
|7
|Spock is a Groovy DSL for unit tests
|https://github.com/spockframework/spock/blob/master/README.md[Spock] tests of **bitcoinj** classes.
|===

[#bitcoinj-cli]
==== bitcoinj-cli: An Bitcoin RPC command-line client

An alternative implementation of `bitcoin-cli` in Java. Built as a fat jar executable with `java -jar`. The command:

[subs="attributes"]
    java -jar bitcoinj-cli-{addons-version}.jar -rpcport=8080 getblockcount

will output:

    Connecting to: http://127.0.0.1:8080/
    0

NOTE: Only a few RPCs are currently supported. Pull requests welcome.

For help type:

[subs="attributes"]
    java -jar bitcoinj-cli-{addons-version}.jar -?

or read the http://msgilligan.github.io/bitcoinj-addons/manpage-bitcoinj-cli.html[manual page].

[#bitcoinj-rpcclient]
==== bitcoinj-rpcclient: A Bitcoin JSON-RPC client using bitcoinj types

If the RPC procedure takes a Bitcoin address as parameter, then the Java method will take an `org.bitcoinj.core.Address`.
If the RPC returns a transaction, the Java method will return an `org.bitcoinj.core.Transaction`.

See the JavaDoc for http://msgilligan.github.io/bitcoinj-addons/apidoc/com/msgilligan/bitcoinj/rpc/BitcoinClient.html[BitcoinClient] to see the methods implemented.

===== Sample Spock Integration Tests

These sample Spock "feature tests" show the RPC client in action and are from the file https://github.com/msgilligan/bitcoinj-addons/blob/master/bitcoinj-rpcclient/src/integ/groovy/com/msgilligan/bitcoinj/rpc/BitcoinSpec.groovy#L31-L55[BitcoinSpec.groovy].

[source,groovy]
----
    def "Use RegTest mode to generate a block upon request"() {
        given: "a certain starting height"
        def startHeight = blockCount

        when: "we generate 1 new block"
        generateBlock()

        then: "the block height is 1 higher"
        blockCount == startHeight + 1
    }

    def "When we send an amount to a newly created address, it arrives"() {
        given: "A new, empty Bitcoin address"
        def destinationAddress = getNewAddress()

        when: "we send it testAmount (from coins mined in RegTest mode)"
        sendToAddress(destinationAddress, testAmount, "comment", "comment-to")

        and: "we generate 1 new block"
        generateBlock()
 
        then: "the new address has a balance of testAmount"
        testAmount == getReceivedByAddress(destinationAddress)
    }
----


[#bitcoinj-json]
==== bitcoinj-json

http://wiki.fasterxml.com/JacksonHome[Jackson] serializers, deserializers & POJOs used to create and parse JSON by both client and server implementations of Bitcoin JSON-RPC.

[#bitcoinj-server]
==== bitcoinj-server

Service objects that power the Daemon and PeerServer. Some objects, such as http://msgilligan.github.io/bitcoinj-addons/apidoc/com/msgilligan/bitcoinj/spring/service/PeerGroupService.html[PeerGroupService], rely solely on http://docs.oracle.com/javase/7/docs/api/javax/annotation/package-summary.html[javax.annotation] and https://docs.oracle.com/javaee/6/api/javax/inject/package-summary.html[javax.inject] for configuration and can be wired with either Spring or (in theory)  https://github.com/google/guice[Guice]. The current focus is on http://projects.spring.io/spring-boot/[Spring Boot], but we're hoping to build a http://ratpack.io[Ratpack] server in the future.

[#bitcoinj-daemon]
==== bitcoinj-daemon

A starting point for building a complete `bitcoind` equivalent using **bitcoinj**. Currently serves a very https://github.com/msgilligan/bitcoinj-addons/blob/master/bitcoinj-json/src/main/java/com/msgilligan/bitcoinj/rpcserver/BitcoinJsonRpc.java[small subset] of the https://bitcoin.org/en/developer-reference#remote-procedure-calls-rpcs[Bitcoin RPC API] (Bitcoin uses http://www.jsonrpc.org[JSON-RPC].)

Uses a `PeerGroup` to power the limited RPCs. Will use a `BlockStore`. (Pull requests welcome.)

Built as a fat, executable jar, so it can be run with `java -jar`.

[#bitcoinj-peerserver]
==== bitcoinj-peerserver

PeerServer is a bitcoinj-powered http://projects.spring.io/spring-boot/[Spring Boot] application that provides the following functions:

. A *Bitcoin JSON-RPC service* at `http://[host]:[port]/bitcoinrpc`
.. This is hard to connect to using `bitcoin-cli` as it expects the RPCs to be accessible at the root path ('/'), but you can use the Java RPC client or CLI tool to talk to it.
.. There may be issues with the security configuration on this URL. We're currently investigating.

. A https://stomp.github.io[STOMP protocol] *WebSocket* service that live-streams pending Bitcoin transactions from the P2P network.
.. The page at `/peers.html` lists connected peers and streams Transactions from the P2P network.
.. You must login using username: `admin`, password: `admin` to view this page.
.. The `peers.html' page is currently unstyled HTML.

No `bitcoind` is required. The server uses a bitcoinj https://bitcoinj.github.io/javadoc/{bitcoinj-version}/org/bitcoinj/core/PeerGroup.html[PeerGroup] to connect directly to the Bitcoin network. I'm considering renaming it to `PeerGroupServer` for this reason. The JAR is entirely self-contained and can be run on any system with Java 8 with the `java -jar peerserver-{addons-version}.jar` command.

[#bitcoinj-money]
==== bitcoinj-money

http://javamoney.github.io[JavaMoney] (also known as http://javamoney.github.io/api.html[JSR 354]) is the new Java Standard for advanced and flexible currency handling on the Java platform.

[quote, JavaMoney Web Site]
JSR 354 provides a portable and extendible framework for handling of Money & Currency. The API models monetary amounts and currencies in a platform independent and portable way, including well defined extension points.

Support for virtual currencies is one of the key design goals in the specification. The `bitcoinj-money` module will allow Bitcoin to
 be used by standard Java APIs in the same ways as fiat currencies.

The JavaMoney Reference Implementation (aka "Moneta") contains implementations of `ExchangeRateProvider` for ECB (European Central Bank) and IMF (International Monetary Fund).
 There is also U.S. FRB (Federal Reserve Bank) and Yahoo Finance `ExchangeRateProvider` in the JavaMoney financial library add-on module.

`bitcoinj-money` contains `BitcoinCurrencyProvider` which will add `"BTC"` as a standard currency code to any applications including the `bitcoinj-money` JAR in its classpath. and `"BTC"` will be available to your applications.

The `bitcoinj-money` module also includes an adapter class `BaseXChangeExchangeRateProvider` that along with a 1-line subclass adapts implementations of the `Exchange` interface in the popular and complete http://knowm.org/open-source/xchange/[XChange] library to be used by JavaMoney-compatible applications.


[#bitcoinj-dsl]
==== bitcoinj-dsl

Groovy DSL support to write things like:

    assert 1.btc == 100_000_000.satoshi

 and

    assert 100.satoshi == Coin.MICROCOIN

[#bitcoinj-spock]
=== bitcoinj-spock

https://github.com/spockframework/spock/blob/master/README.md[Spock] tests of **bitcoinj** classes. Initial focus is learning and documentation, not test coverage.


== Building and Running

Before running `./gradlew` wrapper script you must have JDK 8 installed and your `JAVA_HOME` set correctly. For example:

    export JAVA_HOME=`/usr/libexec/java_home -v1.8`

NOTE: The first time you run the build all dependency JARS will be downloaded.

=== Full Build

    ./gradlew build

=== Build CLI tool

To build the CLI executable jar:

    ./gradlew :bitcoinj-cli:shadowJar

To run it and display a list of command line options:

[subs="attributes"]
    java -jar bitcoinj-cli/build/libs/bitcoinj-cli-{addons-version}.jar -?

=== Build and Run PeerServer Locally Using Gradle

. Build and Run with Gradle Wrapper
    
    ./gradlew :bitcoinj-peerserver:bootRun

NOTE: This will connect to the Bitcoin P2P network

=== Build an Executable JAR

    ./gradlew :bitcoinj-peerserver:assemble

The JAR will be built at `build/libs/peerserver-{addons-version}.jar` and can be run with:

[subs="attributes"]
    java -jar bitcoinj-peerserver/build/libs/peerserver-{addons-version}.jar






