= bitcoinj Add-ons 

image:https://api.bintray.com/packages/msgilligan/maven/bitcoinj-addons/images/download.svg[link="https://bintray.com/msgilligan/maven/bitcoinj-addons/_latestVersion"] image:https://ci.omni.foundation/buildStatus/icon?job=bitcoinj-addons[link="https://ci.omni.foundation/job/bitcoinj-addons/"]

Add-on modules for https://bitcoinj.github.io[bitcoinj], including:

* A *JSON-RPC Java client* for the Bitcoin API
* *bitcoinj-cli* - a command line tool and supporting libraries for accessing the JSON-RPC API.
* Bitcoin server libraries for *server-side JSON-RPC*.
* A Groovy-language *Domain Specific Language* for scripting and testing with *bitcoinj*
* **bitcoinj-daemon** - A framework for a Java-based implementation of bitcoind.
* **bitcoinj-peerserver** - A web application that connects to the P2P network and streams events to a browser using the STOMP protocol over *WebSocket*.
* Functional tests of bitcoind (and bitcoinj-daemon) JSON-RPC services, that run in https://bitcoinj.github.io/testing#regression-test-mode[regression test mode].

WARNING: Do not use this software with your Bitcoin private keys without doing a rigorous audit of the code. (Feedback welcome.)

WARNING: The API is not final and will change without warning.

We're hoping that one or more modules will be accepted into the bitcoinj project. Most of these components are fairly new, but all are useful and ready for pull requests.

== Overview

=== Binaries image:https://api.bintray.com/packages/msgilligan/maven/bitcoinj-addons/images/download.svg[link="https://bintray.com/msgilligan/maven/bitcoinj-addons/_latestVersion"]

Although the API is changing rapidly, binary releases are available on https://bintray.com/msgilligan/maven/bitcoinj-addons/view[Bintray]. You can dowload JARs or use the provided Maven coordinates to link to them directly from your `pom.xml` or `build.gradle`.


=== API Documentation

We jave published http://msgilligan.github.io/bitcoinj-addons/apidoc/index.html[preliminary JavaDoc] to our Github pages site.

=== Continuous Integration image:https://ci.omni.foundation/buildStatus/icon?job=bitcoinj-addons[link="https://ci.omni.foundation/job/bitcoinj-addons/"]

bitcoinj-addons is used by https://github.com/OmniLayer/OmniJ#omnij-project[OmniJ] and is tested by the https://ci.omni.foundation/[Omni Foundation Continuous Integration Server] (self-signed SSL certificate). You can check the https://ci.omni.foundation/job/bitcoinj-addons/[bitcoinj-addons job] for build status.


=== Requirements

* Most modules may use JDK 7 (subset) for Android compatibility (see table, below)
* Server modules (Spring Boot Apps) require JDK 8 or later

=== Modules

See the table below for an overview of the modules.
The *JDK* column indicates the version of Java required.
The *Grooviness* column describes the use of the http://www.groovy-lang.org[Groovy Programming Language] within that module.

.Modules
[cols="3,1,3,5"]
|===
|Name |JDK |Grooviness |Description

|<<bitcoinj-cli,bitcoinj-cli>>
|7
|Tests only
|Command line RPC tool and CLI support/utility classes

|<<bitcoinj-rpcclient,bitcoinj-rpcclient>>
|7
|Optional + tests
|Bitcoin JSON-RPC client

|<<bitcoinj-json,bitcoinj-json>>
|7
|Tests only (TBD)
|Server-side JSON-RPC & Spring support

|<<bitcoinj-daemon,bitcoinj-daemon>>
|8
|Tests only (TBD)
|JSON-RPC bitcoin server daemon -- to replace `bitcoind` someday ;)

|<<bitcoinj-peerserver,bitcoinj-peerserver>>
|8
|Tests only (TBD)
|Peer and transaction info over HTTP + WebSocket/STOMP. JSON-RPC server, too.

|<<bitcoinj-groovy,bitcoinj-groovy>>
|7
|Yeah, baby!
|Groovy DSL support.

|<<bitcoinj-spock,bitcoinj-spock>>
|7
|Spock, baby!
|https://github.com/spockframework/spock/blob/master/README.md[Spock] tests of **bitcoinj** classes.
|===

[#bitcoinj-cli]
==== bitcoinj-cli: An Bitcoin RPC command-line client

An alternative implementation of `bitcion-cli` in Java. Built as a fat jar executable with `java -jar`. The command:

    java -jar bitcoinj-cli-0.0.3.jar -rpcport=8080 getblockcount

will output:

    Connecting to: http://127.0.0.1:8080/
    0

NOTE: Only a few RPCs are currently supported. Pull requests welcome.

[#bitcoinj-rpcclient]
==== bitcoinj-rpcclient: A Bitcoin JSON-RPC client using bitcoinj types

If the RPC procedure takes a Bitcoin address as parameter, then the Java method will take an `org.bitcoinj.core.Address`.
If the RPC returns a transaction, the Java method will return an `org.bitcionj.core.Transaction`.

See the JavaDoc for http://msgilligan.github.io/bitcoinj-addons/apidoc/com/msgilligan/bitcoinj/rpc/BitcoinClient.html[BitcoinClient] to see the methods implemented.

[#bitcoinj-json]
==== bitcoin-json

Server-side JSON components and services that power the Daemon and PeerServer.

[#bitcoinj-daemon]
==== bitcoinj-daemon

A starting point for building a complete `bitcoind` equivalent using **bitcoinj**. Currently serves a very https://github.com/msgilligan/bitcoinj-addons/blob/master/src/main/java/com/msgilligan/bitcoinj/rpc/BitcoinJsonRpc.java[small subset] of the https://bitcoin.org/en/developer-reference#remote-procedure-calls-rpcs[Bitcoin RPC API] (Bitcoin uses http://www.jsonrpc.org[JSON-RPC].)

Uses a `PeerGroup` to power the limited RPCs. Will use a `BlockStore`. (Pull requests welcome.)

Built as a fat, executable jar, so it can be run with `java -jar`.

[#bitcoinj-peerserver]
==== bitcoinj-peerserver

PeerServer is a bitcoinj-powered http://projects.spring.io/spring-boot/[Spring Boot] application that provides the following functions:

. A *Bitcoin JSON-RPC service* at `http://[host]:[port]/bitcoinrpc`
.. This is hard to connect to using `bitcoin-cli` as it expects the RPCs to be accessible at the root path ('/'), but you can use the Java RPC client or CLI tool to talk to it.
.. There may be issues with the security configuration on this URL. We're currently investigating.

. A https://stomp.github.io[STOMP protocol] *WebSocket* service that live-streams pending Bitcoin transactions from the P2P network.
.. The page at `/peers.html` lists connected peers and streams Transactions from the P2P network.
.. You must login using username: `admin`, password: `admin` to view this page.
.. The `peers.html' page is currently unstyled HTML.

No `bitcoind` is required. The server uses a bitcoinj https://bitcoinj.github.io/javadoc/0.13.2/org/bitcoinj/core/PeerGroup.html[PeerGroup] to connect directly to the Bitcoin network. I'm considering renaming it to `PeerGroupServer` for this reason. The JAR is entirely self-contained and can be run on any system with Java 8 with the `java -jar peerserver-0.0.1.jar` command.

[#bitcoinj-groovy]
==== bitcoinj-groovy

Groovy DSL support to write things like:

    assert 1.btc == 100_000_000.satoshi

 and

    assert 100.satoshi == Coin.MICROCOIN

[#bitcoinj-spock]
=== bitcoinj-spock

https://github.com/spockframework/spock/blob/master/README.md[Spock] tests of **bitcoinj** classes. Initial focus is learning and documentation, not test coverage.


== Building and Running

Before running `./gradlew` wrapper script you must have JDK 8 installed and your `JAVA_HOME` set correctly. For example:

    export JAVA_HOME=`/usr/libexec/java_home -v1.8`

NOTE: The first time you run the build all dependency JARS will be downloaded.

=== Full Build

    ./gradlew build

=== Build CLI tool

To build the CLI executable jar:

    ./gradlew :bitcoinj-cli:shadowJar

To run it and display a list of command line options:

    java -jar bitcoinj-cli/build/libs/bitcoinj-cli-0.0.3-SNAPSHOT.jar -?

=== Build and Run PeerServer Locally Using Gradle

. Build and Run with Gradle Wrapper
    
    ./gradlew :bitcoinj-peerserver:bootRun

NOTE: This will connect to the Bitcoin P2P network

=== Build an Exectuable JAR 

    ./gradlew :bitcoinj-peerserver:assemble

The JAR will be built at `build/libs/peerserver-0.0.3-SNAPSHOT.jar` and can be run with:

    java -jar bitcoinj-peerserver/build/libs/peerserver-0.0.3-SNAPSHOT.jar






