= ConsensusJ
Sean Gilligan <https://github.com/msgilligan>
v0.5.4
:description: ConsensusJ README document.
:consensusj-version: 0.5.4
:bitcoinj-version: 0.15.7
:bitcoinj-apidoc: https://bitcoinj.github.io/javadoc/{bitcoinj-version}/
:cj-apidoc: https://consensusj.github.io/consensusj/apidoc
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

image:https://travis-ci.org/ConsensusJ/consensusj.svg?branch=master["Build Status", link="https://travis-ci.org/ConsensusJ/consensusj"] image:https://gitlab.com/ConsensusJ/consensusj/badges/master/pipeline.svg[link="https://gitlab.com/ConsensusJ/consensusj/pipelines",title="pipeline status"] image:https://api.bintray.com/packages/msgilligan/maven/consensusj/images/download.svg[link="https://bintray.com/msgilligan/maven/consensusj/_latestVersion"]

Modular cryptocurrency libraries for Java, JVM languages, and Android. Including:

* A *Java JSON-RPC client* that serves as a base class for _any_ cryptocurrency platform that uses JSON-RPC for communication.
* A *Groovy JSON-RPC client* that can use _dynamic_ methods for scripting, experimentation and functional tests of _any_ JSON-RPC server.
* A *JSON-RPC Java client* for the https://bitcoin.org/en/developer-reference#bitcoin-core-apis[Bitcoin Core API] with strong, static types.
* JSON library using https://github.com/FasterXML/jackson[Jackson] to convert between Bitcoin types and JSON
** *bitcoinj* types <--> JSON (e.g. {bitcoinj-apidoc}/org/bitcoinj/core/Address.html[Address], {bitcoinj-apidoc}/org/bitcoinj/core/Sha256Hash.html[Sha256Hash], {bitcoinj-apidoc}/org/bitcoinj/core/Transaction.html[Transaction])
** Strongly-typed {cj-apidoc}/com/msgilligan/bitcoinj/json/pojo/package-summary.html[Java POJOs] <--> Bitcoin Core standard JSON (e.g. {cj-apidoc}/com/msgilligan/bitcoinj/json/pojo/BlockChainInfo.html[BlockChainInfo], {cj-apidoc}/com/msgilligan/bitcoinj/json/pojo/UnspentOutput.html[UnspentOutput], {cj-apidoc}/com/msgilligan/bitcoinj/json/pojo/ChainTip.html[ChainTip])
* https://spring.io[Spring] and https://github.com/google/guice[Guice]-compatible Bitcoin server components for *server-side JSON-RPC*.
* **bitcoinj-proxy** - A high-performance, non-blocking https://ratpack.io[Ratpack] server for proxying access to *bitcoind* or building Bitcoin-based microservices.
* **bitcoinj-daemon** - A *Spring Boot*-based framework for a Java-based implementation of *bitcoind*.
* **bitcoinj-peerserver** -  A *Spring Boot*-based web application that connects to the Bitcoin P2P network and streams events to a browser using the *STOMP* protocol over *WebSocket*.
* Bitcoin currency and exchange implementations for http://javamoney.github.io[JavaMoney].
* *bitcoinj-cli* - a command line tool and supporting libraries for accessing the JSON-RPC API.
* A Groovy-language *Domain Specific Language* for scripting and testing with *bitcoinj*
* Functional tests of bitcoind (and bitcoinj-daemon) JSON-RPC services, that run in https://bitcoinj.github.io/testing#regression-test-mode[regression test mode].

WARNING: Do not use this software with your private keys without doing a rigorous audit of the code first. (Feedback welcome.)

WARNING: The API is not final and prior to a 1.0 release *may* change without warning. Most of the API changes are fairly manageable though, and we try to deprecate first.

This project is a mono-repo with a large number of submodules/components that are published as independent binary libraries. Since it is easy to pull in just the modules you need via Maven coordinates, this allows you to manage your transitive dependencies and build small, tight applications and servers. Most of these components are fairly new, but all are useful and ready for pull requests.

== Overview

=== Binaries image:https://api.bintray.com/packages/msgilligan/maven/consensusj/images/download.svg[link="https://bintray.com/msgilligan/maven/consensusj/_latestVersion"]

Although the API is changing, binary releases are available on https://bintray.com/msgilligan/maven/consensusj/view[Bintray]. You can download JARs or use the provided Maven coordinates to link to them directly from your `pom.xml` or `build.gradle`.


=== API Documentation

We have published {cj-apidoc}/index.html[preliminary JavaDoc] to our Github pages site.

=== Continuous Integration 

ConsensusJ is used by https://github.com/OmniLayer/OmniJ#omnij-project[OmniJ] and is tested by the https://ci.omni.foundation/[Omni Foundation Continuous Integration Server]. There are also Travis CI and GitLab CI builds.


// Jenkins Widget doesn't display correctly because of ci.omni.foundation self-signed SSL
// image:https://ci.omni.foundation/buildStatus/icon?job=consensusj[link="https://ci.omni.foundation/job/consensusj/"]

* Omni Foundation Jenkins build: https://ci.omni.foundation/job/consensusj/[consensusj job] (note: self-signed SSL certificate)

* Travis CI build:
image:https://travis-ci.org/ConsensusJ/consensusj.svg?branch=master["Build Status", link="https://travis-ci.org/ConsensusJ/consensusj"]

* GitLab CI build: image:https://gitlab.com/ConsensusJ/consensusj/badges/master/pipeline.svg[link="https://gitlab.com/ConsensusJ/consensusj/pipelines",title="pipeline status"]


=== Requirements

* All modules now require *Java 8* (Android 7) or later.
* The command-line tools/libraries now require *Java 9* or later (and will require Java 11 or later after https://github.com/ConsensusJ/consensusj/issues/55[Issue #55: JavaDoc won't build on JDK 11] is resolved.)

=== ConsensusJ Modules

We are in the process of refactoring all modules into the new `org.consensusj` namespace. As part of this process, once all the packages in a module are under `org.consensusj` and there are no split packages, we are assigning JPMS module names via the "Automatic Module" mechanism. This results in a consistent package structure, easier usage by Java 9+, and a smooth migration to JPMS module descriptors.

The new modules also more clearly separate Java from Groovy, so the core Java modules have zero dependencies on Groovy JARs.

.ConsensusJ Modules
[cols="3,1,3,5"]
|===
|Name |Min JDK |Java module name |Description

|<<consensusj-currency,consensusj-currency>>
| 8
| `org.consensusj.currency`
| http://javamoney.github.io[JavaMoney] Currency Provider(s)

|<<consensusj-decentralizedid,consensusj-decentralizedid>>
| 8
| `org.consensusj.decentralizedid`
| Preliminary, experimental, W3C DID and BTCR DID Method support

|<<consensusj-exchange,consensusj-exchange>>
| 8
| `org.consensusj.exchange`
| http://javamoney.github.io[JavaMoney] Exchange Providers. Adapter to use http://knowm.org/open-source/xchange/[XChange] `Exchange` implementations as JavaMoney `ExchangeRateProvider`s.

|<<consensusj-jsonrpc,consensusj-jsonrpc>>
| 8
| `org.consensusj.jsonrpc`
| JSON-RPC client

|<<consensusj-jsonrpc-cli,consensusj-jsonrpc-cli>>
| *9*
| `org.consensusj.jsonrpc.cli`
| JSON-RPC command-line interface (CLI) libraries and tool

|consensusj-jsonrpc-daemon
| 8
| `org.consensusj.jsonrpc.daemon`
| JSON-RPC Sample Server

|<<consensusj-jsonrpc-gvy,consensusj-jsonrpc-gvy>>
| 8
| `org.consensusj.jsonrpc.groovy`
| Groovy JSON-RPC client (dynamic RPC methods)

|<<cj-btc-cli,cj-btc-cli>>
| *9*
| not yet
| Command-line JSON-RPC client for Bitcoin

|<<cj-btc-daemon-mn,cj-btc-daemon-mn>>
| 8
| not yet
|JSON-RPC Bitcoin server daemon prototype, using Micronaut.

|<<cj-btc-jsonrpc,cj-btc-jsonrpc>>
| 8
| not yet
| Java JSON-RPC Bitcoin client

|<<cj-btc-jsonrpc-gvy,cj-btc-jsonrpc-gvy>>
| 8
| not yet
| Groovy JSON-RPC Bitcoin client  (dynamic RPC methods)

|<<cj-btc-services,cj-btc-services>>
| 8
| not yet
| Bitcoin Service-Layer objects - compatible with `javax.inject` (https://jcp.org/en/jsr/detail?id=330[JSR-330])

|<<cj-eth-jsonrpc,cj-eth-jsonrpc>>
| 8
| not yet
| Java JSON-RPC Ethereum client (proof-of-concept)

|<<cj-eth-jsonrpc-gvy,cj-eth-jsonrpc-gvy>>
| 8
| not yet
| Groovy JSON-RPC Ethereum client (dynamic RPC methods)

|<<cj-nmc-daemon,cj-nmc-daemon>>
| 8
| not yet
| Namecoin daemon work-in-progress

|<<cj-nmc-jsonrpc,cj-nmc-jsonrpc>>
| 8
| not yet
| Java JSON-RPC Namecoin client (proof-of-concept)

|<<cj-nmc-jsonrpc-gvy,cj-nmc-jsonrpc-gvy>>
| 8
| not yet
| Groovy JSON-RPC Namecoin client (dynamic RPC methods)



|===

[#consensusj-currency]
==== consensusj-currency

http://javamoney.github.io[JavaMoney] (also known as http://javamoney.github.io/api.html[JSR 354]) is the new Java Standard for advanced and flexible currency handling on the Java platform.

[quote, JavaMoney Web Site]
JSR 354 provides a portable and extensible framework for handling of Money & Currency. The API models monetary amounts and currencies in a platform independent and portable way, including well defined extension points.

Support for virtual currencies is one of the key design goals in the specification. The `consensusj-currency` module allows Bitcoin to
be used by standard Java APIs in the same ways as fiat currencies.

`consensusj-currency` contains `BitcoinCurrencyProvider` which will add `"BTC"` as a standard currency code to any applications that includes the `consensusj-currency` JAR in its classpath.

[#consensusj-exchange]
==== consensusj-exchange

The JavaMoney Reference Implementation (aka "Moneta") contains implementations of `ExchangeRateProvider` for ECB (European Central Bank) and IMF (International Monetary Fund).
There is also U.S. FRB (Federal Reserve Bank) and Yahoo Finance `ExchangeRateProvider` in the JavaMoney financial library add-on module.


The `#consensusj-exchange` module includes an adapter class `BaseXChangeExchangeRateProvider` that adapts implementations of the `Exchange` interface in the popular and complete http://knowm.org/open-source/xchange/[XChange] library to be used by JavaMoney-compatible applications.

[#consensusj-jsonrpc]
==== consensusj-jsonrpc

Java implementation of a JSON-RPC client. {cj-apidoc}/org/consensusj/jsonrpc/RPCClient.html[RPCClient] can be subclassed or called directly using the `send()` method and `Object` parameters.

[#consensusj-jsonrpc-gvy]
==== consensusj-jsonrpc-gvy

Dynamic RPC methods are implemented via the `DynamicRPCFallback` Groovy trait. `DynamicRPCClient` can be used to talk to any JSON-RPC server using standard Java types and Jackson JSON conversion.

[#cj-btc-jsonrpc]
==== cj-btc-jsonrpc

Java Bitcoin JSON-RPC client and supporting types, both bitcoinj types and POJOs for Bitcoin Core JSON.

If the RPC procedure takes a Bitcoin address as parameter, then the Java method will take an `org.bitcoinj.core.Address`.
If the RPC returns a transaction, the Java method will return an `org.bitcoinj.core.Transaction`.

See the JavaDoc for {cj-apidoc}/com/msgilligan/bitcoinj/rpc/BitcoinClient.html[BitcoinClient] to see the methods implemented.

[#cj-btc-jsonrpc-gvy]
==== cj-btc-jsonrpc-gvy

Subclass of Bitcoin JSON-RPC client with fallback to dynamic methods (using `DynamicRPCFallback`). This is useful when new methods are added to the server/protocol and static methods and types haven't been written for them yet.


[#cj-btc-cli]
==== cj-btc-cli: An Bitcoin RPC command-line client

An alternative implementation of `bitcoin-cli` in Java. If converted to a fat jar, it is executable with `java -jar`. The command:

[subs="attributes"]
java -jar cj-btc-cli-{consensusj-version}.jar -rpcport=8080 getblockcount

will output:

    Connecting to: http://127.0.0.1:8080/
    0

NOTE: Only a few RPCs are currently supported. Pull requests welcome.

For help type:

[subs="attributes"]
java -jar bitcoinj-cli-{consensusj-version}.jar -?

or read the https://consensusj.github.io/consensusj/manpage-cj-bitcoin-cli.html[manual page].

=== Legacy Modules

See the table below for an overview of the modules in the old `com.msgilligan` namespace.
The *JDK* column indicates the version of Java required.
The *Grooviness* column describes the use of the http://www.groovy-lang.org[Groovy Programming Language] within that module.

.Legacy Modules
[cols="3,1,3,5"]
|===
|Name |JDK |Grooviness |Description

|<<bitcoinj-rpcclient,bitcoinj-rpcclient>>
|8
|Optional + tests
|Bitcoin JSON-RPC integration tests

|<<bitcoinj-json,bitcoinj-json>>
|8
|Tests only (TBD)
|Jackson serializers, deserializers & POJOs for Bitcoin JSON-RPC

|<<bitcoinj-proxy,bitcoinj-proxy>>
|8
|Tests only (TBD)
|Ratpack-based server for proxying *bitcoind* and/or building microservices.

|<<bitcoinj-daemon,bitcoinj-daemon>>
|8
|Tests only (TBD)
|JSON-RPC Bitcoin server daemon -- equivalent to `bitcoind` when/if finished.

|<<bitcoinj-peerserver,bitcoinj-peerserver>>
|8
|Tests only (TBD)
|Peer and transaction info over HTTP + WebSocket/STOMP. JSON-RPC server, too.

|<<bitcoinj-dsl,bitcoinj-dsl>>
|8
|Uses Groovy
|Groovy DSL support.

|<<bitcoinj-spock,bitcoinj-spock>>
|8
|Spock is a Groovy DSL for unit tests
|https://github.com/spockframework/spock/blob/master/README.md[Spock] tests of **bitcoinj** classes.
|===



[#bitcoinj-rpcclient]
==== bitcoinj-rpcclient: A Bitcoin JSON-RPC client using bitcoinj types

Most of the previous functionality of this module has been moved to the new `org.consensusj` modules. What remains is:

* Bitcoin Core integration test framework and tests (Regression Tests using Spock)
* A Namecoin (NMC) JSON-RPC Client
* An Ethereum (ETH) JSON-RPC Client

The remaining classes will be refactored into 3 new `org.consensusj` modules.

===== Sample Spock Integration Tests

These sample Spock "feature tests" show the RPC client in action and are from the file https://github.com/ConsensusJ/consensusj/blob/master/bitcoinj-rpcclient/src/integ/groovy/com/msgilligan/bitcoinj/rpc/BitcoinSpec.groovy#L31-L55[BitcoinSpec.groovy].

[source,groovy]
----
    def "Use RegTest mode to generate a block upon request"() {
        given: "a certain starting height"
        def startHeight = blockCount

        when: "we generate 1 new block"
        generateBlock()

        then: "the block height is 1 higher"
        blockCount == startHeight + 1
    }

    def "When we send an amount to a newly created address, it arrives"() {
        given: "A new, empty Bitcoin address"
        def destinationAddress = getNewAddress()

        when: "we send it testAmount (from coins mined in RegTest mode)"
        sendToAddress(destinationAddress, testAmount, "comment", "comment-to")

        and: "we generate 1 new block"
        generateBlock()
 
        then: "the new address has a balance of testAmount"
        testAmount == getReceivedByAddress(destinationAddress)
    }
----


[#bitcoinj-json]
==== bitcoinj-json

https://github.com/FasterXML/jackson/wiki[Jackson] serializers, deserializers & POJOs used to create and parse JSON by both client and server implementations of Bitcoin JSON-RPC.

[#cj-btc-services]
==== cj-btc-services

Service-Layer objects that power the Daemon(s) and PeerServer. These objects rely solely on http://docs.oracle.com/javase/7/docs/api/javax/annotation/package-summary.html[javax.annotation] and https://docs.oracle.com/javaee/6/api/javax/inject/package-summary.html[javax.inject] for configuration and can be wired with either Spring, https://docs.micronaut.io/latest/guide/index.html#ioc[Micronaut IOC], or https://github.com/google/guice[Guice].

[#bitcoinj-daemon]
==== bitcoinj-daemon

A starting point for building a complete `bitcoind` equivalent using **bitcoinj**. Currently serves a very https://github.com/ConsensusJ/consensusj/blob/master/bitcoinj-json/src/main/java/com/msgilligan/bitcoinj/rpcserver/BitcoinJsonRpc.java[small subset] of the https://bitcoin.org/en/developer-reference#remote-procedure-calls-rpcs[Bitcoin RPC API] (Bitcoin uses http://www.jsonrpc.org[JSON-RPC].)

Built as a fat, executable jar, so it can be run with `java -jar`.

[#cj-btc-daemon-mn]
==== Experimental Micronaut-based Bitcoin daemon

An experimental port of `bitcoinj-daemon` to https://micronaut.io[Micronaut].

[#bitcoinj-peerserver]
==== bitcoinj-peerserver

PeerServer is a bitcoinj-powered http://projects.spring.io/spring-boot/[Spring Boot] application that provides the following functions:

. A *Bitcoin JSON-RPC service* at `http://[host]:[port]/bitcoinrpc`
.. This is hard to connect to using `bitcoin-cli` as it expects the RPCs to be accessible at the root path ('/'), but you can use the Java RPC client or CLI tool to talk to it.
.. There may be issues with the security configuration on this URL. We're currently investigating.

. A https://stomp.github.io[STOMP protocol] *WebSocket* service that live-streams pending Bitcoin transactions from the P2P network.
.. The page at `/peers.html` lists connected peers and streams Transactions from the P2P network.
.. You must login using username: `admin`, password: `admin` to view this page.
.. The `peers.html' page is currently unstyled HTML.

No `bitcoind` is required. The server uses a bitcoinj https://bitcoinj.github.io/javadoc/{bitcoinj-version}/org/bitcoinj/core/PeerGroup.html[PeerGroup] to connect directly to the Bitcoin network. I'm considering renaming it to `PeerGroupServer` for this reason. The JAR is entirely self-contained and can be run on any system with Java 8 with the `java -jar peerserver-{consensusj-version}.jar` command.

[#bitcoinj-proxy]
==== bitcoinj-proxy

A https://ratpack.io[Ratpack]-based proxy server that can proxy JSON-RPC commands to a connected *bitcoind* (or *Omni Core*) server. It can also be used as a starting point for JSON-RPC interoperable microservices.



[#bitcoinj-dsl]
==== bitcoinj-dsl

Groovy DSL support to write things like:

    assert 1.btc == 100_000_000.satoshi

 and

    assert 100.satoshi == Coin.MICROCOIN

[#bitcoinj-spock]
=== bitcoinj-spock

https://github.com/spockframework/spock/blob/master/README.md[Spock] tests of **bitcoinj** classes. Initial focus is learning and documentation, not test coverage.


== Building and Running

Before running `./gradlew` wrapper script you must have JDK 8 installed and your `JAVA_HOME` set correctly. For example:

    export JAVA_HOME=`/usr/libexec/java_home -v1.8`

NOTE: The first time you run the build all dependency JARS will be downloaded.

=== Full Build

    ./gradlew build

=== Build JSON-RPC CLI tool

To build the CLI executable jar:

    ./gradlew :consensusj-jsonrpc-cli:shadowJar

To run it and display a list of command line options:

[subs="attributes"]
    java -jar consensusj-jsonrpc-cli/build/libs/consensusj-jsonrpc-cli-{consensusj-version}.jar -?

=== Build Bitcoin CLI tool

To build the CLI executable jar:

    ./gradlew :cj-btc-cli:shadowJar

To run it and display a list of command line options:

[subs="attributes"]
    java -jar cj-btc-cli/build/libs/cj-btc-cli-{consensusj-version}.jar -?

=== Build and Run PeerServer Locally Using Gradle

. Build and Run with Gradle Wrapper
    
    ./gradlew :bitcoinj-peerserver:bootRun

NOTE: This will connect to the Bitcoin P2P network

=== Build an Executable JAR

    ./gradlew :bitcoinj-peerserver:assemble

The JAR will be built at `build/libs/peerserver-{consensusj-version}.jar` and can be run with:

[subs="attributes"]
    java -jar bitcoinj-peerserver/build/libs/peerserver-{consensusj-version}.jar






