= ConsensusJ
Sean Gilligan <https://github.com/msgilligan>
v0.5.8
:description: ConsensusJ README document.
:consensusj-version: 0.5.8
:bitcoinj-version: 0.15.10
:bitcoinj-apidoc: https://bitcoinj.github.io/javadoc/{bitcoinj-version}/
:cj-apidoc: https://consensusj.github.io/consensusj/apidoc
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

image:https://github.com/ConsensusJ/consensusj/workflows/Gradle%20Build/badge.svg?branch=master["Github Actions Gradle Build", link="https://github.com/ConsensusJ/consensusj/actions?query=workflow%3A%22Gradle+Build%22"] image:https://github.com/ConsensusJ/consensusj/actions/workflows/graalvm.yml/badge.svg?branch=master["Github Actions GraalVM Builds", link="https://github.com/ConsensusJ/consensusj/actions/workflows/graalvm.yml"] image:https://github.com/ConsensusJ/consensusj/workflows/Bitcoin%20Core%20RegTest/badge.svg?branch=master["Github Actions Bitcoin Core RegTest", link="https://github.com/ConsensusJ/consensusj/actions?query=workflow%3A%22Bitcoin+Core+RegTest%22"] image:https://travis-ci.com/ConsensusJ/consensusj.svg?branch=master["Build Status", link="https://travis-ci.com/github/ConsensusJ/consensusj"] image:https://gitlab.com/ConsensusJ/consensusj/badges/master/pipeline.svg[link="https://gitlab.com/ConsensusJ/consensusj/pipelines",title="pipeline status"]


Modular cryptocurrency libraries for Java, JVM languages, and Android.

== Features

=== Core JSON-RPC Features
* A *Java* JSON-RPC client that serves as a base class for _any_ cryptocurrency platform that uses JSON-RPC for communication.
* A *Groovy* JSON-RPC client that can use _dynamic_ methods for scripting, experimentation and functional tests of _any_ JSON-RPC server.
* A JSON-RPC *command-line* client, `jsonrpc`, for testing and debugging JSON-RPC servers and applications. It can be natively compiled with https://www.graalvm.org[GraalVM]. It can launch, call the server and print output in under 50 milliseconds.
* **consensusj-jsonrpc-daemon** - A *Micronaut*-based JSON-RPC "echo" *server*. It can be natively compiled using https://www.graalvm.org[GraalVM].

=== Bitcoin Features

* A *JSON-RPC Java client* for the https://bitcoin.org/en/developer-reference#bitcoin-core-apis[Bitcoin Core API] with strong, static types.
* JSON library using https://github.com/FasterXML/jackson[Jackson] to convert between Bitcoin types and JSON
** *bitcoinj* types <--> JSON (e.g. {bitcoinj-apidoc}/org/bitcoinj/core/Address.html[Address], {bitcoinj-apidoc}/org/bitcoinj/core/Sha256Hash.html[Sha256Hash], {bitcoinj-apidoc}/org/bitcoinj/core/Transaction.html[Transaction])
** Strongly-typed {cj-apidoc}/com/msgilligan/bitcoinj/json/pojo/package-summary.html[Java POJOs] <--> Bitcoin Core standard JSON (e.g. {cj-apidoc}/com/msgilligan/bitcoinj/json/pojo/BlockChainInfo.html[BlockChainInfo], {cj-apidoc}/com/msgilligan/bitcoinj/json/pojo/UnspentOutput.html[UnspentOutput], {cj-apidoc}/com/msgilligan/bitcoinj/json/pojo/ChainTip.html[ChainTip])
* `jakarta.inject`-compatible Bitcoin server components for *server-side JSON-RPC*.
* **cj-btc-daemon** - A *Micronaut*-based framework for a Java-based implementation of *bitcoind*. It can be natively compiled using https://www.graalvm.org[GraalVM].
* *cj-btc-cli* - a command line tool and supporting libraries for accessing the JSON-RPC API.
* A Groovy-language *Domain Specific Language* for scripting and testing with *bitcoinj*
* Functional tests of bitcoind (and bitcoinj-daemon) JSON-RPC services, that run in https://bitcoinj.github.io/testing#regression-test-mode[regression test mode].

=== JavaMoney and Exchange Support

* Bitcoin currency provider implementation for http://javamoney.github.io[JavaMoney].
* Multi-currency exchange "ticker" implementations using http://javamoney.github.io[JavaMoney] and http://knowm.org/open-source/xchange/[XChange].

=== JSON-RPC for Ethereum and Namecoin

* Proof-of-concept Java and Groovy JSON-RPC clients for Ethereum (ETH)
* Proof-of-concept Java and Groovy JSON-RPC clients for Namecoin (NMC)

WARNING: Do not use this software with your private keys without doing a rigorous audit of the code first. (Feedback welcome.)

WARNING: The API is not final and prior to a 1.0 release *may* change without warning. Most of the API changes are fairly manageable though, and we try to deprecate before making significant changes.

=== Many small modules to help you manage dependencies

This project is a mono-repo with many submodules/components that are published as independent binary libraries. Since it is easy to pull in just the modules you need via Maven coordinates, this allows you to manage your transitive dependencies and build lightweight, fast-starting, applications and servers. Fewer dependencies also helps with natively-compiled, Java Module System-based (including `jlink`) applications.

== Overview

=== Binaries

Although the API is changing, binary packages are available on https://gitlab.com/ConsensusJ/consensusj/-/packages[Gitlab.com]. You can download JARs or use the provided Maven coordinates to link to them directly from your `pom.xml` or `build.gradle`.

==== Maven

Add the following to your `pom.xml`:

[source]
----
<repositories>
  <repository>
    <id>gitlab-maven</id>
    <url>https://gitlab.com/api/v4/projects/8482916/packages/maven</url>
  </repository>
</repositories>
----

==== Gradle

Add the following to the `repositories` section of your `build.gradle`:

[source]
----
    maven { url 'https://gitlab.com/api/v4/projects/8482916/packages/maven' }
----


=== API Documentation

We have published {cj-apidoc}/index.html[preliminary JavaDoc] to our Github pages site.

=== Continuous Integration 

* Github Actions: image:https://github.com/ConsensusJ/consensusj/workflows/Gradle%20Build/badge.svg?branch=master["Github Actions Gradle Build", link="https://github.com/ConsensusJ/consensusj/actions?query=workflow%3A%22Gradle+Build%22"] image:https://github.com/ConsensusJ/consensusj/actions/workflows/graalvm.yml/badge.svg?branch=master["Github Actions GraalVM Builds", link="https://github.com/ConsensusJ/consensusj/actions/workflows/graalvm.yml"] image:https://github.com/ConsensusJ/consensusj/workflows/Bitcoin%20Core%20RegTest/badge.svg?branch=master["Github Actions Bitcoin Core RegTest", link="https://github.com/ConsensusJ/consensusj/actions?query=workflow%3A%22Bitcoin+Core+RegTest%22"]

* Travis CI build:
image:https://travis-ci.com/ConsensusJ/consensusj.svg?branch=master["Build Status", link="https://travis-ci.com/ConsensusJ/consensusj"]

* GitLab CI build: image:https://gitlab.com/ConsensusJ/consensusj/badges/master/pipeline.svg[link="https://gitlab.com/ConsensusJ/consensusj/pipelines",title="pipeline status"]


// Jenkins Widget doesn't display correctly because of ci.omni.foundation self-signed SSL
// image:https://ci.omni.foundation/buildStatus/icon?job=consensusj[link="https://ci.omni.foundation/job/consensusj/"]

//* Omni Foundation Jenkins build: https://ci.omni.foundation/job/consensusj/[consensusj job] (note: self-signed SSL certificate)



=== Requirements

* Most modules now require *Java 8* (Android 7) or later.
* The server and command-line tools/libraries now require *Java 11* or later.

=== ConsensusJ Modules

We are in the process of refactoring all modules into the new `org.consensusj` namespace. As part of this process, once all the packages in a module are under `org.consensusj` and there are no split packages, we are assigning JPMS module names via the "Automatic Module" mechanism. This results in a consistent package structure, easier usage by Java 9+, and a smooth migration to JPMS module descriptors.

NOTE:: This module table is slightly out-of-date and will be updated shortly (there are some new "incubating" modules that are not listed.) See the `CHANGELOG` for relevant changes.

.Core JSON-RPC Modules
[cols="3,1,3,5"]
|===
|Name |Min JDK |Java module name |Description

|<<consensusj-jsonrpc,consensusj-jsonrpc>>
| 8
| `org.consensusj.jsonrpc`
| JSON-RPC client

|<<consensusj-jsonrpc-gvy,consensusj-jsonrpc-gvy>>
| 8
| `org.consensusj.jsonrpc.groovy`
| Groovy JSON-RPC client (dynamic RPC methods)

|<<consensusj-jsonrpc-cli,consensusj-jsonrpc-cli>>
| *11*
| `org.consensusj.jsonrpc.cli`
| JSON-RPC command-line interface (CLI) libraries and tool

|<<consensusj-jsonrpc-daemon, consensusj-jsonrpc-daemon>>
| *11*
| `org.consensusj.jsonrpc.daemon`
| JSON-RPC Sample Server

|===

.Bitcoin Modules
[cols="3,1,3,5"]
|===
|Name |Min JDK |Java module name |Description

|<<cj-btc-json,cj-btc-json>>
|8
|not yet
|Jackson serializers, deserializers & POJOs for Bitcoin JSON-RPC

|<<cj-btc-jsonrpc,cj-btc-jsonrpc>>
| 8
| not yet
| Java JSON-RPC Bitcoin client

|<<cj-btc-jsonrpc-gvy,cj-btc-jsonrpc-gvy>>
| 8
| not yet
| Groovy JSON-RPC Bitcoin client  (dynamic RPC methods)

|<<cj-btc-cli,cj-btc-cli>>
| *11*
| not yet
| Command-line JSON-RPC client for Bitcoin

|<<cj-btc-daemon,cj-btc-daemon>>
| *11*
| not yet
|JSON-RPC Bitcoin server daemon prototype, using Micronaut.

|<<cj-btc-services,cj-btc-services>>
| *11*
| not yet
| Bitcoin Service-Layer objects - compatible with `jakarta.inject` (https://jcp.org/en/jsr/detail?id=330[JSR-330])

|<<cj-btc-jsonrpc-integ-test,cj-btc-jsonrpc-integ-test>>
|8
|not yet
|Bitcoin JSON-RPC integration tests (RegTest)


|<<cj-bitcoinj-dsl-gvy,cj-bitcoinj-dsl-gvy>>
|8
|not yet
|Groovy DSL support.

|<<cj-bitcoinj-spock,cj-bitcoinj-spock>>
|8
|not yet
|https://github.com/spockframework/spock/blob/master/README.md[Spock] tests of **bitcoinj** classes.
|===

.JavaMoney and Exchange Rate Support
[cols="3,1,3,5"]
|===
|Name |Min JDK |Java module name |Description

|<<consensusj-currency,consensusj-currency>>
| 8
| `org.consensusj.currency`
| http://javamoney.github.io[JavaMoney] Currency Provider(s)

|<<consensusj-exchange,consensusj-exchange>>
| 8
| `org.consensusj.exchange`
| http://javamoney.github.io[JavaMoney] Exchange Providers. Adapter to use http://knowm.org/open-source/xchange/[XChange] `Exchange` implementations as JavaMoney `ExchangeRateProvider`s.

|===

.Miscellaneous Modules
[cols="3,1,3,5"]
|===
|Name |Min JDK |Java module name |Description

|<<cj-eth-jsonrpc,cj-eth-jsonrpc>>
| 8
| not yet
| Java JSON-RPC Ethereum client (proof-of-concept)

|<<cj-eth-jsonrpc-gvy,cj-eth-jsonrpc-gvy>>
| 8
| not yet
| Groovy JSON-RPC Ethereum client (dynamic RPC methods)

|<<cj-nmc-jsonrpc,cj-nmc-jsonrpc>>
| 8
| not yet
| Java JSON-RPC Namecoin client (proof-of-concept)

|<<cj-nmc-jsonrpc-gvy,cj-nmc-jsonrpc-gvy>>
| 8
| not yet
| Groovy JSON-RPC Namecoin client (dynamic RPC methods)

|<<consensusj-decentralizedid, consensusj-decentralizedid>>
| 8
| `org.consensusj.decentralizedid`
| Preliminary, experimental, W3C DID and BTCR DID Method support

|===

[#consensusj-jsonrpc]
==== consensusj-jsonrpc

Java implementation of a JSON-RPC client. {cj-apidoc}/org/consensusj/jsonrpc/RPCClient.html[RPCClient] can be subclassed or called directly using the `send()` method and `Object` parameters.

[#consensusj-jsonrpc-gvy]
==== consensusj-jsonrpc-gvy

Dynamic RPC methods are implemented via the `DynamicRPCFallback` Groovy trait. `DynamicRPCClient` can be used to talk to any JSON-RPC server using standard Java types and Jackson JSON conversion.

[#cj-btc-jsonrpc]
==== cj-btc-jsonrpc

Java Bitcoin JSON-RPC client and supporting types, both bitcoinj types and POJOs for Bitcoin Core JSON.

If the RPC procedure takes a Bitcoin address as parameter, then the Java method will take an `org.bitcoinj.core.Address`.
If the RPC returns a transaction, the Java method will return an `org.bitcoinj.core.Transaction`.

See the JavaDoc for {cj-apidoc}/com/msgilligan/bitcoinj/rpc/BitcoinClient.html[BitcoinClient] to see the methods implemented.

[#cj-btc-jsonrpc-gvy]
==== cj-btc-jsonrpc-gvy

Subclass of Bitcoin JSON-RPC client with fallback to dynamic methods (using `DynamicRPCFallback`). This is useful when new methods are added to the server/protocol and static methods and types haven't been written for them yet.



[#cj-btc-cli]
==== cj-btc-cli: An Bitcoin RPC command-line client

An alternative implementation of `bitcoin-cli` in Java. If converted to a fat jar, it is executable with `java -jar`. The command:

[subs="attributes"]
java -jar cj-btc-cli-{consensusj-version}.jar -rpcport=8080 getblockcount

will output:

    Connecting to: http://127.0.0.1:8080/
    0

NOTE: Only a few RPCs are currently supported. Pull requests welcome.

For help type:

[subs="attributes"]
java -jar bitcoinj-cli-{consensusj-version}.jar -?

or read the https://consensusj.github.io/consensusj/manpage-cj-bitcoin-cli.html[manual page].




[#cj-btc-json]
==== cj-btc-json

https://github.com/FasterXML/jackson/wiki[Jackson] serializers, deserializers & POJOs used to create and parse JSON by both client and server implementations of Bitcoin JSON-RPC.

[#cj-btc-services]
==== cj-btc-services

Service-Layer object(s) that power the Daemon. These objects rely solely on https://docs.oracle.com/javase/8/docs/api/javax/annotation/package-summary.html[javax.annotation] and https://jakarta.ee/specifications/dependency-injection/2.0/apidocs/jakarta/inject/package-summary.html[jakarta.inject] for configuration and can be wired with Spring, https://docs.micronaut.io/latest/guide/index.html#ioc[Micronaut IOC], or https://github.com/google/guice[Guice].

Built as a fat, executable jar, so it can be run with `java -jar`.

[#cj-btc-daemon]
==== Experimental Micronaut-based Bitcoin daemon

An experimental port of `bitcoinj-daemon` to https://micronaut.io[Micronaut].

A starting point for building a complete `bitcoind` equivalent using **bitcoinj**. It currently serves a small subset of the https://bitcoin.org/en/developer-reference#remote-procedure-calls-rpcs[Bitcoin RPC API] (Bitcoin uses http://www.jsonrpc.org[JSON-RPC].)

It builds as a native binary using GraalVM.


[#cj-bitcoinj-dsl-gvy]
==== cj-bitcoinj-dsl-gvy

Groovy DSL support to write things like:

    assert 1.btc == 100_000_000.satoshi

 and

    assert 100.satoshi == Coin.MICROCOIN

[#cj-bitcoinj-spock]
=== cj-bitcoinj-spock

https://github.com/spockframework/spock/blob/master/README.md[Spock] tests of **bitcoinj** classes. Initial focus is learning and documentation, not test coverage.

[#cj-btc-jsonrpc-integ-test]
==== cj-btc-jsonrpc-integ-test: RegTest mode integration tests using JSON-RPC

Bitcoin Core integration test framework and tests (Regression Tests using Spock)

===== Sample Spock Integration Tests

These sample Spock "feature tests" show the RPC client in action and are from the file https://github.com/ConsensusJ/consensusj/blob/master/bitcoinj-rpcclient/src/integ/groovy/com/msgilligan/bitcoinj/rpc/BitcoinSpec.groovy#L31-L55[BitcoinSpec.groovy].

[source,groovy]
----
    def "Use RegTest mode to generate a block upon request"() {
        given: "a certain starting height"
        def startHeight = blockCount

        when: "we generate 1 new block"
        generateBlock()

        then: "the block height is 1 higher"
        blockCount == startHeight + 1
    }

    def "When we send an amount to a newly created address, it arrives"() {
        given: "A new, empty Bitcoin address"
        def destinationAddress = getNewAddress()

        when: "we send it testAmount (from coins mined in RegTest mode)"
        sendToAddress(destinationAddress, testAmount, "comment", "comment-to")

        and: "we generate 1 new block"
        generateBlock()

        then: "the new address has a balance of testAmount"
        testAmount == getReceivedByAddress(destinationAddress)
    }
----

[#consensusj-currency]
==== consensusj-currency

http://javamoney.github.io[JavaMoney] (also known as http://javamoney.github.io/api.html[JSR 354]) is the new Java Standard for advanced and flexible currency handling on the Java platform.

[quote, JavaMoney Web Site]
JSR 354 provides a portable and extensible framework for handling of Money & Currency. The API models monetary amounts and currencies in a platform independent and portable way, including well defined extension points.

Support for virtual currencies is one of the key design goals in the specification. The `consensusj-currency` module allows Bitcoin to
be used by standard Java APIs in the same ways as fiat currencies.

`consensusj-currency` contains `BitcoinCurrencyProvider` which will add `"BTC"` as a standard currency code to any applications that includes the `consensusj-currency` JAR in its classpath.

[#consensusj-exchange]
==== consensusj-exchange

The JavaMoney Reference Implementation (aka "Moneta") contains implementations of `ExchangeRateProvider` for ECB (European Central Bank) and IMF (International Monetary Fund).
There is also U.S. FRB (Federal Reserve Bank) and Yahoo Finance `ExchangeRateProvider` in the JavaMoney financial library add-on module.


The `#consensusj-exchange` module includes an adapter class `BaseXChangeExchangeRateProvider` that adapts implementations of the `Exchange` interface in the popular and complete http://knowm.org/open-source/xchange/[XChange] library to be used by JavaMoney-compatible applications.



== Building and Running

Before running `./gradlew` wrapper script you must have JDK 11 installed and your `JAVA_HOME` set correctly. To build native images you'll need a GraalVM JDK 11 with the `native-image` tool installed via `gu install native-image`.

NOTE: The first time you run the build all dependency JARS will be downloaded.

=== Full Build

    ./gradlew build

=== Build JSON-RPC CLI tool

To build the CLI executable jar:

    ./gradlew :consensusj-jsonrpc-cli:nativeImage

To run it and display a list of command line options:

    consensusj-jsonrpc-cli/build/jsonrpc -?

[#consensusj-jsonrpc-cli]
=== Build Bitcoin CLI tool

To build the CLI executable jar:

    ./gradlew :cj-btc-cli:nativeImage

To run it and display a list of command line options:

    cj-btc-cli/build/cj-btc-cli -?

[#consensusj-jsonrpc-daemon]
=== Build and Run JSON-RPC Echo daemon

To build and run from Gradle:
    
    ./gradlew :consensusj-jsonrpc-daemon:run

To build a native image and run:

    ./gradlew :consensusj-jsonrpc-daemon:nativeImage
    consensusj-jsonrpc-daemon/build/jsonrpc-echod

=== Build and Run JSON-RPC Bitcoin daemon

To build and run from Gradle:

    ./gradlew :cj-btc-daemon:run

To build a native image and run:

    ./gradlew :cj-btc-daemon:nativeImage
    cj-btc-daemon/build/jbitcoind








