= bitcoinj Add-ons 

image::https://api.bintray.com/packages/msgilligan/maven/bitcoinj-addons/images/download.svg[link="https://bintray.com/msgilligan/maven/bitcoinj-addons/_latestVersion"]

This repository is work-in-progress on some add-on modules for https://bitcoinj.github.io[bitcoinj]. We're hoping that one or more will be accepted into the bitcoinj project.

WARNING: The API is not final and will change without warning.

== Requirements

* Most components require JDK 8 or later
* Some modules may use JDK 7 (subset) for Android compatibility (see table, below)

== Modules

See the table below for an overview of the modules.
The *JDK* column indicates the version of Java required.
The *Grooviness* column describes the use of the http://www.groovy-lang.org[Groovy Programming Language] within that module.

.Modules
[cols="3,1,3,5"]
|===
|Name |JDK |Grooviness |Description

|<<bitcoinj-cli,bitcoinj-cli>>
|7
|Tests only
|Command line RPC tool and CLI support/utility classes

|<<bitcoinj-rpcclient,bitcoinj-rpcclient>>
|7
|Optional + tests
|Bitcoin JSON-RPC client

|<<bitcoinj-json,bitcoinj-json>>
|7
|Tests only (TBD)
|Server-side JSON-RPC & Spring support

|<<bitcoinj-daemon,bitcoinj-daemon>>
|8
|Tests only (TBD)
|JSON-RPC bitcoin server daemon -- to replace `bitcoind` someday ;)

|<<bitcoinj-peerserver,bitcoinj-peerserver>>
|8
|Tests only (TBD)
|Peer and transaction info over HTTP + WebSocket/STOMP. JSON-RPC server, too.

|<<bitcoinj-groovy,bitcoinj-groovy>>
|7
|Yeah, baby!
|Groovy DSL support.

|<<bitcoinj-spock,bitcoinj-spock>>
|7
|Spock, baby!
|https://github.com/spockframework/spock/blob/master/README.md[Spock] tests of **bitcoinj** classes.
|===

[#bitcoinj-cli]
=== bitcoinj-cli: An Bitcoin RPC command-line client

An alternative implementation of `bitcion-cli` in Java. Built as a fat jar executable with `java -jar`. The command:

    java -jar bitcoinj-cli-0.0.3.jar -rpcport=8080 getblockcount

will output:

    Connecting to: http://127.0.0.1:8080/
    0

NOTE: Only a few RPCs are currently supported. Pull requests welcome.

[#bitcoinj-rpcclient]
=== bitcoinj-rpcclient: A Bitcoin JSON-RPC client using bitcoinj types

It the RPC takes a Bitcoin address as parameter, the Java method will take an `org.bitcionj.core.Address`.
If it returns a transaction it returns an `org.bitcionj.core.Transaction`.

[#bitcoinj-json]
=== bitcoin-json

Server-side JSON components and services that power the Daemon and PeerServer.

[#bitcoinj-daemon]
=== bitcoinj-daemon

A starting point for building a complete `bitcoind` equivalent using **bitcoinj**. Currently serves a very https://github.com/msgilligan/bitcoinj-addons/blob/master/src/main/java/com/msgilligan/bitcoinj/rpc/BitcoinJsonRpc.java[small subset] of the https://bitcoin.org/en/developer-reference#remote-procedure-calls-rpcs[Bitcoin RPC API] (Bitcoin uses http://www.jsonrpc.org[JSON-RPC].)

Uses a `PeerGroup` to power the limited RPCs. Will use a `BlockStore`. (Pull requests welcome.)

Built as a fat, executable jar, so it can be run with `java -jar`.

[#bitcoinj-peerserver]
=== bitcoinj-peerserver

PeerServer is a bitcoinj-powered http://projects.spring.io/spring-boot/[Spring Boot] application that provides the following functions:

. A *Bitcoin JSON-RPC service* at `http://[host]:[port]/bitcoinrpc`
.. This is hard to connect to using `bitcoin-cli` as it expects the RPCs to be accessible at the root path ('/'), but you can use the Java RPC client or CLI tool to talk to it.
.. There may be issues with the security configuration on this URL. We're currently investigating.

. A https://stomp.github.io[STOMP protocol] *WebSocket* service that live-streams pending Bitcoin transactions from the P2P network.
.. The page at `/peers.html` lists connected peers and streams Transactions from the P2P network.
.. You must login using username: `admin`, password: `admin` to view this page.
.. The `peers.html' page is currently unstyled HTML.

No `bitcoind` is required. The server uses a bitcoinj https://bitcoinj.github.io/javadoc/0.13.2/org/bitcoinj/core/PeerGroup.html[PeerGroup] to connect directly to the Bitcoin network. I'm considering renaming it to `PeerGroupServer` for this reason. The JAR is entirely self-contained and can be run on any system with Java 8 with the `java -jar peerserver-0.0.1.jar` command.

[#bitcoinj-groovy]
=== bitcoinj-groovy

Groovy DSL support to write things like:

    assert 1.btc == 100_000_000.satoshi

 and

    assert 100.satoshi == Coin.MICROCOIN

[#bitcoinj-spock]
=== bitcoinj-spock

https://github.com/spockframework/spock/blob/master/README.md[Spock] tests of **bitcoinj** classes. Initial focus is learning and documentation, not test coverage.


== Building and Running

Before running `./gradlew` wrapper script you must have JDK 8 installed and your `JAVA_HOME` set correctly. For example:

    export JAVA_HOME=`/usr/libexec/java_home -v1.8`

NOTE: The first time you run the build all dependency JARS will be downloaded.

=== Full Build

    ./gradlew build

=== Build CLI tool

To build the CLI executable jar:

    ./gradlew :bitcoinj-cli:shadowJar

To run it and display a list of command line options:

    java -jar bitcoinj-cli/build/libs/bitcoinj-cli-0.0.3-SNAPSHOT.jar -?

=== Build and Run PeerServer Locally Using Gradle

. Build and Run with Gradle Wrapper
    
    ./gradlew :bitcoinj-peerserver:bootRun

NOTE: This will connect to the Bitcoin P2P network

=== Build an Exectuable JAR 

    ./gradlew :bitcoinj-peerserver:assemble

The JAR will be built at `build/libs/peerserver-0.0.3-SNAPSHOT.jar` and can be run with:

    java -jar bitcoinj-peerserver/build/libs/peerserver-0.0.3-SNAPSHOT.jar






