= ConsensusJ User Guide
Sean Gilligan
v0.2, May 6, 2018: First draft
:numbered:
:toc:
:toclevels: 3
:linkattrs:
:imagesdir: images

Paragraph TBD.

== Introduction to ConsensusJ

This section is TBD. For now the project https://github.com/ConsensusJ/consensusj/blob/master/README.adoc[README] is the best place to get started.

== JSON-RPC Clients

[plantuml, format="png", id="Class Diagram"]
....
skinparam packageStyle Rect
skinparam shadowing false
hide empty members

namespace com.msgilligan.jsonrpc {
    interface UntypedRPCClient
    abstract class AbstractRPCClient

    class RPCClient

    interface DynamicRPCFallback << Groovy, trait >>
    class DynamicRPCClient << Groovy >>

    UntypedRPCClient <|.. AbstractRPCClient
    AbstractRPCClient <|-- RPCClient

    UntypedRPCClient <|.. DynamicRPCFallback
    RPCClient <|-- DynamicRPCClient
    DynamicRPCFallback <|.. DynamicRPCClient
}

namespace com.msgilligan.bitcoinj.rpc {
    class BitcoinClient
    class BitcoinExtendedClient

    class BitcoinScriptingClient << Groovy >>
    class BitcoinCLIClient << Groovy >>


    com.msgilligan.jsonrpc.RPCClient <|-- BitcoinClient
    BitcoinClient <|-- BitcoinExtendedClient
    BitcoinExtendedClient <|-- BitcoinScriptingClient
    com.msgilligan.jsonrpc.DynamicRPCFallback <|.. BitcoinScriptingClient
    BitcoinClient <|-- BitcoinCLIClient
}

namespace com.msgilligan.namecoinj.rpc {
    class NamecoinClient
    class NamecoinScriptingClient << Groovy >>

    com.msgilligan.bitcoinj.rpc.BitcoinClient <|-- NamecoinClient
    NamecoinClient <|.. NamecoinScriptingClient
    com.msgilligan.jsonrpc.DynamicRPCFallback <|.. NamecoinScriptingClient
}

namespace foundation.omni.rpc {
    class OmniClient
    class OmniScriptingClient << Groovy >>
    class OmniCLIClient << Groovy >>


    com.msgilligan.bitcoinj.rpc.BitcoinExtendedClient <|-- OmniClient
    OmniClient <|-- OmniScriptingClient
    com.msgilligan.jsonrpc.DynamicRPCFallback <|.. OmniScriptingClient
    OmniClient <|-- OmniCLIClient
}
....

