= ConsensusJ User Guide
Sean Gilligan
v0.6.1, June 1, 2023: Draft
:numbered:
:toc:
:toclevels: 3
:linkattrs:
:imagesdir: images
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
//:dot: /opt/homebrew/bin/dot
:mmdc: /opt/homebrew/bin/mmdc

Paragraph TBD.

== Introduction to ConsensusJ

This section is TBD. For now the project https://github.com/ConsensusJ/consensusj/blob/master/README.adoc[README] is the best place to get started.


== JSON-RPC Clients

=== Generic

The module `consensusj-jsonrpc` contains `JsonRpcClientHttpUrlConnection` which is a generic JSON-RPC client.

=== Bitcoin


The module `cj-btc-jsonrpc` contains `BitcoinClient` and `ExtendedBitcoinClient`. 


=== Class Diagrams

For some class diagrams see <<rpc-client-inheritance.adoc#, ConsensusJ JSON-RPC Inheritance>>.


== Module Dependency Graphs

=== consensusj-rx-zeromq

This module is independent of the core JSON-RPC clients. It has no dependencies on **bitcoinj**, or anything cryptocurrency or JSON-RPC related.

[mermaid]
----
flowchart TD
    consensusj-rx-zeromq --> RxJava3
    consensusj-rx-zeromq --> JeroMQ

classDef external fill:#999;
class RxJava3 external;
class JeroMQ external;
----

=== Core JSON-RPC

The core JSON-RPC modules have no dependencies on **bitcoinj** or anything cryptocurrency-related.

[mermaid]
----
flowchart TD
    consensusj-jsonrpc --> Jackson
    consensusj-jsonrpc-gvy --> Groovy
    consensusj-jsonrpc-gvy --> consensusj-jsonrpc
    consensusj-jsonrpc-cli --> Commons-CLI
    consensusj-jsonrpc-cli --> consensusj-jsonrpc
    consensusj-jrpc-echod --> consensusj-jsonrpc
    consensusj-jrpc-echod --> Micronaut
    consensusj-rx-jsonrpc --> consensusj-jsonrpc
    consensusj-rx-jsonrpc --> RxJava3

classDef external fill:#999;
class Jackson external;
class Groovy external;
class Commons-CLI external;
class Micronaut external;
class RxJava3 external;
class JeroMQ external;
----
