= cj-bitcoin-cli(1)
Sean Gilligan
:doctype: manpage
:man manual: consensusj Manual
:man source: consensusj 0.5.1
:page-layout: base

== NAME

cj-bitcoin-cli - A Bitcoin API command-line client

== SYNOPSIS

cj-bitcoin-cli [_OPTION_]... _command_...  [_ARGUMENT_]...

== DESCRIPTION

cj-bitcoin-cli(1) sends _command_... [_ARGUMENT_]... to the Bitcoin RPC server specified via [_OPTION_]... or the default server at `http://localhost:8332`.

By default it reads from the local `bitcoin.conf` for host, port, username, and password information.

== OPTIONS

=== Connection Settings

*-regtest*::
  Server is in *RegTest* mode, connect to the RegTest port (18443).

*-testnet*::
  Server is running on TestNet, connect to the TestNet port (18332).

*--rpcconnect*=_HOST_::
  Hostname or IP of server to connect to.
  Defaults to _localhost_.

*--rpcport*=_HOST_::
  TCP port for connection.
  Defaults to _8332_.

*--rpcuser*=_HOST_::
  Username for connection.
  Defaults to "".

*--rpcpassword*=_HOST_::
  Password for connection.
  Defaults to "".

*--rpcssl*::
  Use HTTPS / SSL for the connection.

WARNING: SSL cert validation temporarily disabled to support self-signed certificates.

*--rpcwait*::
  Wait for `bitcoind` to start up.

=== Program Information

*-?::
  Show the help message.

== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; configuration error; unexpected error).

== EXAMPLES

* getblockcount to default server or server configured in `bitcoin.conf`:
+
------------
$ cj-bitcoin-cli getblockcount
------------

* getconnectioncount to `bitcoinj-daemon` running on its default port:
+
------------
$ cj-bitcoin-cli -rpcport=8080 getconnectioncount
------------



== BUGS

Refer to the *ConsensusJ* issue tracker at https://github.com/ConsensusJ/consensusj/issues.

== AUTHORS

*cj-bitcoin-cli* was written by Sean Gilligan.

*consensusj* was written by Sean Gilligan and DexX7.

*bitcoinj* was written by the bitcoinj project team.

== RESOURCES

*Git source repository on GitHub:* https://github.com/ConsensusJ/consensusj

== COPYING

Copyright \(C) 2014-2018 Sean Gilligan.
Free use of this software is granted under the terms of the Apache Software License v2.
