= ConsensusJ JSON-RPC Client Inheritance
Sean Gilligan
v0.1, June 1, 2023: First version as separate document
:numbered:
:toc:
:toclevels: 3
:linkattrs:
:imagesdir: images
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
//:dot: /opt/homebrew/bin/dot

Paragraph TBD.

== Overview

This document is a new document containing the PlantUML diagrams previously in the <<consensusj-user-guide#, ConsensusJ User Guide>>.

== JSON-RPC Clients

The following diagram shows the basic class hierarchy of the core `org.consensusj.jsonrpc` and `org.consensusj.bitcoin.jsonrpc` modules.

[plantuml, format="svg", id="class-diagram-java"]
....
skinparam packageStyle Rect
skinparam shadowing false
hide empty members

namespace org.consensusj.jsonrpc {
    interface JsonRpcClient
    interface JacksonRpcClient
    abstract class AbstractRPCClient
    class JsonRpcClientHttpUrlConnection

    JsonRpcClient <|.. JacksonRpcClient
    JacksonRpcClient <|.. AbstractRPCClient
    AbstractRPCClient <|-- JsonRpcClientHttpUrlConnection

}


namespace org.consensusj.bitcoin.jsonrpc {
    class BitcoinClient
    class BitcoinExtendedClient



    org.consensusj.jsonrpc.JsonRpcClientHttpUrlConnection <|-- BitcoinClient
    BitcoinClient <|-- BitcoinExtendedClient
}

....

=== Groovy

By implementing the `DynamicRPCMethodFallback` `trait` we can layer dynamic JSON-RPC methods on top of static JSON-RPC methods. The following diagram leaves out some details to focus on the `DynamicRPCClient`. It _extends_ `JsonRpcClientHttpUrlConnection` and _implements_ the `DynamicRPCMethodFallback` `trait`. By doing this, it inherits the (static) methods of  `JsonRpcClientHttpUrlConnection` and falls back to dynamic method resolution for any additional method names that are used.

[plantuml, format="svg", id="class-diagram-groovy"]
....
skinparam packageStyle Rect
skinparam shadowing false
hide empty members

namespace org.consensusj.jsonrpc {
    interface JsonRpcClient
    class JsonRpcClientHttpUrlConnection

    JsonRpcClient <|..JsonRpcClientHttpUrlConnection

}

namespace org.consensusj.jsonrpc.groovy {
  interface DynamicRPCMethodFallback << Groovy, trait >>
  class DynamicRPCClient << Groovy >>

  org.consensusj.jsonrpc.JsonRpcClient <|.. DynamicRPCMethodFallback
  org.consensusj.jsonrpc.JsonRpcClientHttpUrlConnection <|-- DynamicRPCClient
  DynamicRPCMethodFallback <|.. DynamicRPCClient
}

....

The following diagram (which also leaves out some details), shows how the `BitcoinScriptingClient` extends `BitcoinExtendedClient` but adds dynamic methods by implementing the `DynamicRPCMethodFallback` `trait`.

[plantuml, format="svg", id="class-diagram-groovy-bitcoin"]
....
skinparam packageStyle Rect
skinparam shadowing false
hide empty members

namespace org.consensusj.jsonrpc {
    interface JsonRpcClient
}

namespace org.consensusj.jsonrpc.groovy {
  interface DynamicRPCMethodFallback << Groovy, trait >>

  org.consensusj.jsonrpc.JsonRpcClient <|.. DynamicRPCMethodFallback
}

namespace org.consensusj.bitcoin.jsonrpc {
    class BitcoinExtendedClient

    org.consensusj.jsonrpc.JsonRpcClient <|.. BitcoinExtendedClient
}

namespace org.consensusj.bitcoin.jsonrpc.groovy {

    class BitcoinScriptingClient << Groovy >>


    org.consensusj.jsonrpc.groovy.DynamicRPCMethodFallback <|.. BitcoinScriptingClient
    org.consensusj.bitcoin.jsonrpc.BitcoinExtendedClient <|-- BitcoinScriptingClient
}

....
