name: Gradle Build

on: [push, pull_request]

jobs:
  validate_gradle_wrapper:
    name: "Validate Gradle Wrapper"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4

  build_gradle:
    needs: validate_gradle_wrapper
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: ['17', '21', '24']
        distribution: ['temurin']
      fail-fast: false
    name: ${{ matrix.os }} JDK ${{ matrix.java }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew buildCI installDist --scan --info --stacktrace
    - name: Generate SHA256SUMS (Linux)
      run: sha256sum artifacts/*/* > SHA256SUMS
      working-directory: ./build
      if: runner.os == 'Linux'
    - name: Generate SHA256SUMS (macOS)
      run: shasum -a 256 artifacts/*/* > SHA256SUMS
      working-directory: ./build
      if: runner.os == 'macOS'
    - name: Upload SHA256SUMS
      uses: actions/upload-artifact@v4
      with:
        name: SHA256SUMS-${{ matrix.os }}-${{ matrix.java }}
        path: build/SHA256SUMS
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts-${{ matrix.os }}-${{ matrix.java }}
        path: build/artifacts
